<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hello hkit, lets complete the test form</name>
   <tag></tag>
   <elementGuidId>8b6e2650-0d16-40b1-81d5-6de0665c8d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='greetings']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#greetings</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>761645f7-58cb-45da-ab91-5fb720aeb605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>greetings</value>
      <webElementGuid>d4a5bc60-671e-4896-9733-d90cb316f53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello hkit, let's complete the test form:</value>
      <webElementGuid>a9a254fe-313a-4fdc-b0b3-dd886b08a71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;greetings&quot;)</value>
      <webElementGuid>69ccd00c-7843-4a6f-8eea-bbc41d01c015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='greetings']</value>
      <webElementGuid>937497ab-5f68-46cd-bf29-a9144c7a5ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageProfile']/p</value>
      <webElementGuid>6490f13d-960a-4a55-a674-c3847dc77c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestProject Example page'])[2]/following::p[1]</value>
      <webElementGuid>47224681-68d8-49ff-a399-a464855df6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[1]</value>
      <webElementGuid>5ec24536-2796-45e5-8d97-aa9d773740fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/preceding::p[1]</value>
      <webElementGuid>5f84bd2a-2aad-4f64-9255-1a1844652a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hello']/parent::*</value>
      <webElementGuid>e8eb2db6-d364-4caa-9929-cf0c12d46535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>68bb0d49-78f1-4f40-b80e-72c0c568544d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'greetings' and (text() = concat(&quot;Hello hkit, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;) or . = concat(&quot;Hello hkit, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;))]</value>
      <webElementGuid>239b7d03-2184-4fc7-ba5a-f03c55c17fea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
