<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hello hkit, lets complete the test form</name>
   <tag></tag>
   <elementGuidId>a3f4cbdd-f91b-4ed7-8989-cb308f3c3329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='greetings']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#greetings</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4e26e1c6-11ad-4244-809c-ea135383f085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>greetings</value>
      <webElementGuid>b8e6a0e8-751d-4fe8-87d3-89efda2dc748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello hkit, let's complete the test form:</value>
      <webElementGuid>5001823d-0241-4a31-867d-addf5c13090f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;greetings&quot;)</value>
      <webElementGuid>a80df763-a35c-4cc6-8aaf-9feb363e0467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='greetings']</value>
      <webElementGuid>c577685d-f613-4d96-a7d4-4a9de962f648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageProfile']/p</value>
      <webElementGuid>fa6b960c-22af-4d18-bb74-435d850d579a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestProject Example page'])[2]/following::p[1]</value>
      <webElementGuid>bdf466ec-b794-4dec-b0cc-9fad1eb45950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[1]</value>
      <webElementGuid>2ae9108c-6c10-4eac-af45-e6bbc17501bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/preceding::p[1]</value>
      <webElementGuid>ef0019e5-0190-44aa-bbd6-32f558db17ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hello']/parent::*</value>
      <webElementGuid>db599db9-fbfc-46d6-9d0c-55f47dbd5d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>4602f6a5-b246-45d9-9464-73b0afb78ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'greetings' and (text() = concat(&quot;Hello hkit, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;) or . = concat(&quot;Hello hkit, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;))]</value>
      <webElementGuid>3e2d4455-5088-42f2-b6b1-54d8f13b6b0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
